name: ESLint

on:
  pull_request:
    branches: [main, develop]
  pull_request_target:
    branches: [main, develop]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    # See details at https://github.com/ad-m/github-push-action/
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fix Eslint issues
        run: npm run eslint:fix

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "Fixed eslint issues" || true

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: ${{ github.ref }}

      - name: Check again to validate all issues are fixed
        run: npm run eslint
